print(2+3)
print(x) # exception
